sudo: false
language: ruby
rvm:
  - 2.3.1
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
script: bundle exec rspec
matrix:
  include:
    - name: "GraphQL 1.9.x"
      env: GRAPHQL_GEM_VERSION=1.9
    - name: "GraphQL 1.8.x"
      env: GRAPHQL_GEM_VERSION=1.8
